blueprint:
  name: SwitchBot Dual Motor Stop
  description: Long curtain (>3m) needs 2 motors and work in sync
  author: BlueDiamond
  domain: script

  input:
    cover_id_master:
      name: Curtain master
      description: At the end of the curtain, traveling the most distance
      selector:
        entity:
          domain: cover
          device_class: curtain
    cover_id_slave:
      name: Curtain slave
      description: At the middle of the curtain, traveling the lowest distance
      selector:
        entity:
          domain: cover
          device_class: curtain
    script_open:
      name: Script curtain open
      description: Stop script when it's running
      selector:
        entity:
          domain: script
    script_close:
      name: Script curtain close
      description: Stop script when it's running
      selector:
        entity:
          domain: script
    script_position:
      name: Script curtain position
      description: Stop script when it's running
      selector:
        entity:
          domain: script

mode: restart
max_exceeded: silent

sequence:
  - service: script.turn_off
    target:
      entity_id:
        - !input script_open
        - !input script_close
        - !input script_position
  - service: cover.stop_cover
    target:
      entity_id:
        - !input cover_id_master
        - !input cover_id_slave
